application:
  name: My Application

server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

google:
  service:
    account:
      type: service_account
      project_id: YOUR_PROJECT_ID_HERE
      private_key_id: YOUR_PRIVATE_KEY_ID_HERE
      private_key: |
        -----BEGIN PRIVATE KEY-----
        YOUR_PRIVATE_KEY_HERE
        -----END PRIVATE KEY-----
      client_email: YOUR_CLIENT_EMAIL_HERE
      client_id: 'YOUR_CLIENT_ID_HERE'
      auth_uri: https://accounts.google.com/o/oauth2/auth
      token_uri: https://oauth2.googleapis.com/token
      auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
      client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/YOUR_CLIENT_EMAIL_HERE
